name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/SotoLamongan.jpeg
    - assets/BaksoMalang.jpeg
    - assets/Rawon.jpeg
    - assets/RujakCingur.jpeg
    - assets/RujakSoto.jpeg
    - assets/LontongBalap.jpeg
    - assets/LontongKupang.jpeg
    - assets/PecelSemanggi.jpeg
    - assets/PecelTumpang.jpeg
    - assets/TahuTek.jpeg
    - assets/TahuCampur.jpeg
    - assets/SateMadura.jpeg
    - assets/NasiTempong.jpeg
    - assets/NasiKrawu.jpeg
    - assets/BandengAsap.jpg
    
    
